<a href="https://colab.research.google.com/github/beakdu/collaboration/blob/main/8%EC%9E%A5_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84%EC%9D%B8%EB%8D%B1%EC%8A%A4%EC%A1%B0%EC%9E%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


In [2]:
np.random.rand(3,5)

array([[0.46821217, 0.71036332, 0.71395658, 0.86076009, 0.01428093],
       [0.73691321, 0.88274949, 0.9269354 , 0.55643097, 0.44263313],
       [0.18975042, 0.01472805, 0.32391995, 0.7656802 , 0.29576853]])

In [3]:
np.round(np.random.rand(3,5),2)  # 실수자리를 2자리로

array([[0.53, 0.34, 0.96, 0.93, 0.61],
       [0.23, 0.98, 0.99, 0.09, 0.91],
       [0.7 , 0.26, 0.54, 0.23, 0.09]])

In [5]:
np.round(np.random.rand(3,5),2).T

array([[0.06, 0.8 , 0.57],
       [0.49, 0.51, 0.85],
       [0.62, 0.51, 0.3 ],
       [0.34, 0.64, 0.78],
       [0.95, 0.06, 0.31]])

In [6]:
list('ABCED')

['A', 'B', 'C', 'E', 'D']

In [7]:
tmp_frm = pd.DataFrame(np.vstack([list('ABCDE'),np.round(np.random.rand(3,5),2)]).T, columns=['col01','col02','col03','col04']) #vstack은 열을 추가하는 것이므로 행의 개수가 같아야 함

In [8]:
tmp_frm

col01 col02 col03 col04
0     A  0.99   0.2  0.59
1     B  0.45  0.74  0.01
2     C  0.15   0.6  0.93
3     D  0.91  0.31   0.0
4     E  0.22  0.35   0.0

In [10]:
print('set_index - 특정한 열을 인덱스로 설정할때-')
tmp_frm.set_index('col01')

set_index - 특정한 열을 인덱스로 설정할때-


col02 col03 col04
col01                  
A      0.99   0.2  0.59
B      0.45  0.74  0.01
C      0.15   0.6  0.93
D      0.91  0.31   0.0
E      0.22  0.35   0.0

In [11]:
tmp_frm

col01 col02 col03 col04
0     A  0.99   0.2  0.59
1     B  0.45  0.74  0.01
2     C  0.15   0.6  0.93
3     D  0.91  0.31   0.0
4     E  0.22  0.35   0.0

In [12]:
tmp_frm.set_index('col01',inplace=True)

In [13]:
tmp_frm

col02 col03 col04
col01                  
A      0.99   0.2  0.59
B      0.45  0.74  0.01
C      0.15   0.6  0.93
D      0.91  0.31   0.0
E      0.22  0.35   0.0

In [15]:
tmp_frm.reset_index()

col01 col02 col03 col04
0     A  0.99   0.2  0.59
1     B  0.45  0.74  0.01
2     C  0.15   0.6  0.93
3     D  0.91  0.31   0.0
4     E  0.22  0.35   0.0

In [16]:
tmp_frm

col02 col03 col04
col01                  
A      0.99   0.2  0.59
B      0.45  0.74  0.01
C      0.15   0.6  0.93
D      0.91  0.31   0.0
E      0.22  0.35   0.0

In [17]:
tmp_frm.reset_index(inplace=True)
tmp_frm

col01 col02 col03 col04
0     A  0.99   0.2  0.59
1     B  0.45  0.74  0.01
2     C  0.15   0.6  0.93
3     D  0.91  0.31   0.0
4     E  0.22  0.35   0.0

In [21]:
print('다중 인덱스 -열')
multi_frm =pd.DataFrame(np.round(np.random.randn(5,4),2),columns=[['Grp01','Grp01','Grp2','Grp2'],# 구릅인덱스,
                                                               ['col01','col02','col01','col02']]) # 컬럼인덱스

다중 인덱스 -열


In [22]:
multi_frm

Grp01        Grp2      
  col01 col02 col01 col02
0 -0.54  1.04 -0.89  0.63
1  0.43  1.94  1.10 -1.04
2 -0.75  0.77 -1.91  0.23
3  2.01 -0.15 -1.31  0.16
4  0.28  0.68  1.07  0.34

In [24]:
multi_frm.columns.names=['GrpIdx','ColIdx']
multi_frm # 그룹과 컬럼에 대한 인덱스 부여로 코드상 이점을 높일수 있음

GrpIdx Grp01        Grp2      
ColIdx col01 col02 col01 col02
0      -0.54  1.04 -0.89  0.63
1       0.43  1.94  1.10 -1.04
2      -0.75  0.77 -1.91  0.23
3       2.01 -0.15 -1.31  0.16
4       0.28  0.68  1.07  0.34

In [27]:
print('다중인덱스 -행')
multi_frm = pd.DataFrame(np.round(np.random.randn(6,4),2),columns=[['Grp01','Grp01','Grp02','Grp02'],
                                                                   ['col01','col02','col01','col02'],],
                         index=[
                             ['m','m','m','f','f','f'],
                             ['id_'+str(i+1) for i in range(6)]
                         ])

다중인덱스 -행


In [28]:
multi_frm

Grp01       Grp02      
       col01 col02 col01 col02
m id_1 -0.27  0.78  0.84 -0.03
  id_2  0.23 -0.20  1.77  0.75
  id_3  0.39  0.69  0.26  0.51
f id_4  0.71  0.64  1.04  0.55
  id_5 -1.90  1.62 -0.25  0.51
  id_6  0.06  0.96 -0.50  0.36

In [29]:
multi_frm.columns.names=['GrpIdx','ColIdx']

In [30]:
multi_frm

GrpIdx Grp01       Grp02      
ColIdx col01 col02 col01 col02
m id_1 -0.27  0.78  0.84 -0.03
  id_2  0.23 -0.20  1.77  0.75
  id_3  0.39  0.69  0.26  0.51
f id_4  0.71  0.64  1.04  0.55
  id_5 -1.90  1.62 -0.25  0.51
  id_6  0.06  0.96 -0.50  0.36

In [31]:
multi_frm.index.names=['gender','idx']

In [32]:
multi_frm

GrpIdx      Grp01       Grp02      
ColIdx      col01 col02 col01 col02
gender idx                         
m      id_1 -0.27  0.78  0.84 -0.03
       id_2  0.23 -0.20  1.77  0.75
       id_3  0.39  0.69  0.26  0.51
f      id_4  0.71  0.64  1.04  0.55
       id_5 -1.90  1.62 -0.25  0.51
       id_6  0.06  0.96 -0.50  0.36

In [36]:
multi_frm.unstack()

GrpIdx Grp01                                                      ... Grp02  \
ColIdx col01                              col02                   ... col01   
idx     id_1  id_2  id_3  id_4 id_5  id_6  id_1 id_2  id_3  id_4  ...  id_3   
gender                                                            ...         
f        NaN   NaN   NaN  0.71 -1.9  0.06   NaN  NaN   NaN  0.64  ...   NaN   
m      -0.27  0.23  0.39   NaN  NaN   NaN  0.78 -0.2  0.69   NaN  ...  0.26   

GrpIdx                                                       
ColIdx                  col02                                
idx     id_4  id_5 id_6  id_1  id_2  id_3  id_4  id_5  id_6  
gender                                                       
f       1.04 -0.25 -0.5   NaN   NaN   NaN  0.55  0.51  0.36  
m        NaN   NaN  NaN -0.03  0.75  0.51   NaN   NaN   NaN  

[2 rows x 24 columns]

In [39]:
print('다중 인덱스의 경우 인덱싱은 어떻게?-')
print('튜플형식 접근하면 된다')
multi_frm[[('Grp01','col01'),('Grp02','col02')]]


다중 인덱스의 경우 인덱싱은 어떻게?-
튜플형식 접근하면 된다


GrpIdx      Grp01 Grp02
ColIdx      col01 col02
gender idx             
m      id_1 -0.27 -0.03
       id_2  0.23  0.75
       id_3  0.39  0.51
f      id_4  0.71  0.55
       id_5 -1.90  0.51
       id_6  0.06  0.36

In [34]:
print('인덱스를 바꿀 수 있는데요-')
print('stack(): 열 ->행')
print('unstack():행 ->열')

인덱스를 바꿀 수 있는데요-
stack(): 열 ->행
unstack():행 ->열


In [35]:
multi_frm.stack()

<ipython-input-35-6e5de5780c18>:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  multi_frm.stack()


GrpIdx              Grp01  Grp02
gender idx  ColIdx              
m      id_1 col01   -0.27   0.84
            col02    0.78  -0.03
       id_2 col01    0.23   1.77
            col02   -0.20   0.75
       id_3 col01    0.39   0.26
            col02    0.69   0.51
f      id_4 col01    0.71   1.04
            col02    0.64   0.55
       id_5 col01   -1.90  -0.25
            col02    1.62   0.51
       id_6 col01    0.06  -0.50
            col02    0.96   0.36

In [41]:
# 행 인덱스 정보까지 같이 가져오기위해 loc사용
multi_frm.loc[[('m','id_1')],:] #m의 id_1번인 사람만 가져오기


GrpIdx      Grp01       Grp02      
ColIdx      col01 col02 col01 col02
gender idx                         
m      id_1 -0.27  0.78  0.84 -0.03

In [42]:
multi_frm.loc['m'] #m그룹에 대한 데이터정보 확인 가능

GrpIdx Grp01       Grp02      
ColIdx col01 col02 col01 col02
idx                           
id_1   -0.27  0.78  0.84 -0.03
id_2    0.23 -0.20  1.77  0.75
id_3    0.39  0.69  0.26  0.51

In [48]:
print('다중 인덱스 정렬')
print('level 속성- 기준')
print('axis 축 지정 -')
multi_frm.sort_index(level=0)
multi_frm.sort_index(level=0, axis =1)


다중 인덱스 정렬
level 속성- 기준
axis 축 지정 -


GrpIdx      Grp01       Grp02      
ColIdx      col01 col02 col01 col02
gender idx                         
m      id_1 -0.27  0.78  0.84 -0.03
       id_2  0.23 -0.20  1.77  0.75
       id_3  0.39  0.69  0.26  0.51
f      id_4  0.71  0.64  1.04  0.55
       id_5 -1.90  1.62 -0.25  0.51
       id_6  0.06  0.96 -0.50  0.36